class AddForeignKeys2 < ActiveRecord::Migration
  def up
    execute 'ALTER TABLE clients ADD CONSTRAINT FK_clients_rate_id FOREIGN KEY (rate_id) REFERENCES rates(id)'
    execute 'ALTER TABLE clients ADD CONSTRAINT FK_clients_main_contact_id FOREIGN KEY (main_contact_id) REFERENCES contacts(id)'
    execute 'ALTER TABLE clients ADD CONSTRAINT FK_clients_billing_contact_id FOREIGN KEY (billing_contact_id) REFERENCES contacts(id)'
    execute 'ALTER TABLE clients ADD CONSTRAINT FK_clients_payment_term_id FOREIGN KEY (payment_term_id) REFERENCES payment_terms(id)'
    execute 'ALTER TABLE expense_entries ADD CONSTRAINT FK_expense_entries_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices(id)'
    execute 'ALTER TABLE expenses ADD CONSTRAINT FK_expenses_firm_id FOREIGN KEY (firm_id) REFERENCES firms(id)'
    execute 'ALTER TABLE invoices ADD CONSTRAINT FK_invoices_client_id FOREIGN KEY (client_id) REFERENCES clients(id)'
    execute 'ALTER TABLE invoices ADD CONSTRAINT FK_invoices_contact_id FOREIGN KEY (contact_id) REFERENCES contacts(id)'
    execute 'ALTER TABLE matters ADD CONSTRAINT FK_matters_rate_id FOREIGN KEY (rate_id) REFERENCES rates(id)'
    execute 'ALTER TABLE matters ADD CONSTRAINT FK_matters_responsible_user_id FOREIGN KEY (responsible_user_id) REFERENCES users(id)'
    execute 'ALTER TABLE matters ADD CONSTRAINT FK_matters_payment_term_id FOREIGN KEY (payment_term_id) REFERENCES payment_terms(id)'
    execute 'ALTER TABLE matters ADD CONSTRAINT FK_matters_main_contact_id FOREIGN KEY (main_contact_id) REFERENCES contacts(id)'
    execute 'ALTER TABLE matters ADD CONSTRAINT FK_matters_billing_contact_id FOREIGN KEY (billing_contact_id) REFERENCES contacts(id)'
    execute 'ALTER TABLE payment_allocates ADD CONSTRAINT FK_payment_allocates_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id)'
    execute 'ALTER TABLE payment_allocates ADD CONSTRAINT FK_payment_allocates_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices(id)'
    execute 'ALTER TABLE payment_terms ADD CONSTRAINT FK_payment_terms_firm_id FOREIGN KEY (firm_id) REFERENCES firms(id)'
    execute 'ALTER TABLE payments ADD CONSTRAINT FK_payments_client_id FOREIGN KEY (client_id) REFERENCES clients(id)'
    execute 'ALTER TABLE payments ADD CONSTRAINT FK_payments_matter_id FOREIGN KEY (matter_id) REFERENCES matters(id)'
    execute 'ALTER TABLE rates ADD CONSTRAINT FK_rates_firm_id FOREIGN KEY (firm_id) REFERENCES firms(id)'
    execute 'ALTER TABLE time_entries ADD CONSTRAINT FK_time_entries_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices(id)'
  end

  def down
    execute 'ALTER TABLE clients DROP CONSTRAINT FK_clients_rate_id'
    execute 'ALTER TABLE clients DROP CONSTRAINT FK_clients_main_contact_id'
    execute 'ALTER TABLE clients DROP CONSTRAINT FK_clients_billing_contact_id'
    execute 'ALTER TABLE clients DROP CONSTRAINT FK_clients_payment_term_id'
    execute 'ALTER TABLE expense_entries DROP CONSTRAINT FK_expense_entries_invoice_id'
    execute 'ALTER TABLE expenses DROP CONSTRAINT FK_expenses_firm_id'
    execute 'ALTER TABLE invoices DROP CONSTRAINT FK_invoices_client_id'
    execute 'ALTER TABLE invoices DROP CONSTRAINT FK_invoices_contact_id'
    execute 'ALTER TABLE matters DROP CONSTRAINT FK_matters_rate_id'
    execute 'ALTER TABLE matters DROP CONSTRAINT FK_matters_responsible_user_id'
    execute 'ALTER TABLE matters DROP CONSTRAINT FK_matters_payment_term_id'
    execute 'ALTER TABLE matters DROP CONSTRAINT FK_matters_main_contact_id'
    execute 'ALTER TABLE matters DROP CONSTRAINT FK_matters_billing_contact_id'
    execute 'ALTER TABLE payment_allocates DROP CONSTRAINT FK_payment_allocates_payment_id'
    execute 'ALTER TABLE payment_allocates DROP CONSTRAINT FK_payment_allocates_invoice_id'
    execute 'ALTER TABLE payment_terms DROP CONSTRAINT FK_payment_terms_firm_id'
    execute 'ALTER TABLE payments DROP CONSTRAINT FK_payments_client_id'
    execute 'ALTER TABLE payments DROP CONSTRAINT FK_payments_matter_id'
    execute 'ALTER TABLE rates DROP CONSTRAINT FK_rates_firm_id'
    execute 'ALTER TABLE time_entries DROP CONSTRAINT FK_time_entries_invoice_id'
  end
end
