require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MattersController do

  # This should return the minimal set of attributes required to create a valid
  # Matter. As you add validations to Matter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all matters as @matters" do
      matter = Matter.create! valid_attributes
      get :index
      assigns(:matters).should eq([matter])
    end
  end

  describe "GET show" do
    it "assigns the requested matter as @matter" do
      matter = Matter.create! valid_attributes
      get :show, :id => matter.id.to_s
      assigns(:matter).should eq(matter)
    end
  end

  describe "GET new" do
    it "assigns a new matter as @matter" do
      get :new
      assigns(:matter).should be_a_new(Matter)
    end
  end

  describe "GET edit" do
    it "assigns the requested matter as @matter" do
      matter = Matter.create! valid_attributes
      get :edit, :id => matter.id.to_s
      assigns(:matter).should eq(matter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Matter" do
        expect {
          post :create, :matter => valid_attributes
        }.to change(Matter, :count).by(1)
      end

      it "assigns a newly created matter as @matter" do
        post :create, :matter => valid_attributes
        assigns(:matter).should be_a(Matter)
        assigns(:matter).should be_persisted
      end

      it "redirects to the created matter" do
        post :create, :matter => valid_attributes
        response.should redirect_to(Matter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved matter as @matter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matter.any_instance.stub(:save).and_return(false)
        post :create, :matter => {}
        assigns(:matter).should be_a_new(Matter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matter.any_instance.stub(:save).and_return(false)
        post :create, :matter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested matter" do
        matter = Matter.create! valid_attributes
        # Assuming there are no other matters in the database, this
        # specifies that the Matter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Matter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => matter.id, :matter => {'these' => 'params'}
      end

      it "assigns the requested matter as @matter" do
        matter = Matter.create! valid_attributes
        put :update, :id => matter.id, :matter => valid_attributes
        assigns(:matter).should eq(matter)
      end

      it "redirects to the matter" do
        matter = Matter.create! valid_attributes
        put :update, :id => matter.id, :matter => valid_attributes
        response.should redirect_to(matter)
      end
    end

    describe "with invalid params" do
      it "assigns the matter as @matter" do
        matter = Matter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Matter.any_instance.stub(:save).and_return(false)
        put :update, :id => matter.id.to_s, :matter => {}
        assigns(:matter).should eq(matter)
      end

      it "re-renders the 'edit' template" do
        matter = Matter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Matter.any_instance.stub(:save).and_return(false)
        put :update, :id => matter.id.to_s, :matter => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested matter" do
      matter = Matter.create! valid_attributes
      expect {
        delete :destroy, :id => matter.id.to_s
      }.to change(Matter, :count).by(-1)
    end

    it "redirects to the matters list" do
      matter = Matter.create! valid_attributes
      delete :destroy, :id => matter.id.to_s
      response.should redirect_to(matters_url)
    end
  end

end
